name: schedule

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v3.4.1
      
      - name: Install dependencies
        run: |
          yarn
      
      - name: Run node
        run: |
          yarn start
